name: shell-linter
on:
  pull_request:
    branches:
      - master

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
